### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by JodyPayne** [AustP/austs-one-click-node#10]
I am running both Voi and Algo nodes, and they crashed from what could be a maxed out memory issue. 

When I enable telemetry, the Voi RAM usage jumps from 278MB to 7.8GB within 20 minutes, while the Algo node jumps from 350Mbs to 1.5GB. Then, when I disable the telemetry, the Voi node drops back to the 278 MB range, and Algo stays the same.

**Comment by cswenor** [comment]
This is a potential work around from dragmz:
go to command line:
rundll32 sysdm.cpl,EditEnvironmentVariables

User Variables -> New... -> Variable name = GOMEMLIMIT, Variable value = xGiB (e.g. 8 GiB) -> OK -> OK

Restart the node 
This will affect all the Go processes running on that user though. It's the one click that should set the env var when spawning algod so this is just a workaround.

Not sure if it will work but it's an idea.

**Comment by IRLalgo** [comment]
> This is a potential work around from dragmz: go to command line: rundll32 sysdm.cpl,EditEnvironmentVariables
> 
> User Variables -> New... -> Variable name = GOMEMLIMIT, Variable value = xGiB (e.g. 8 GiB) -> OK -> OK
> 
> Restart the node This will affect all the Go processes running on that user though. It's the one click that should set the env var when spawning algod so this is just a workaround.
> 
> Not sure if it will work but it's an idea.

I tried & that did not resolved the problem for me. 
My node running on windows (1CN) just keeps getting booted with the telemetry on (& haven't been booted once with the telemetry off). 
(IDK if it's also worth noting... I am not experiencing the same problems on my older & slower Macbook's 1CN)

**Comment by dragmz** [comment]
https://github.com/algorand/go-algorand/pull/5745 will fix it on Windows so the GOMEMLIMIT hack is no longer needed

**Comment by AustP** [comment]
I merged in @dragmz patch into the binaries and released v1.3.1 with those binaries. Initial reports seem good so anyone who has this problem, make sure to try the latest version.
