### ISSUE TITLE
The node could not be started

### ISSUE THREAD

**Issue by nyanez1976** [AustP/austs-one-click-node#11]
I received this error after reinstalling. Note, I thought I did it wrong the first time and deleted it and after reviewing the video it appears I just needed to wait for it to sync to link my wallet.  But now I've reinstalled it and get this error.

couldn't initialize the node: reloadLedger.loadFromDisk tracker *ledger.accountUpdates failed to loadFromDisk : ledger does not have entry 2 (latest 32180000, committed 32180000)

**Comment by AustP** [comment]
Hmm haven't seen this one yet. What OS are you using? How much disk space do you have?

**Comment by nyanez1976** [comment]
Thanks for responding.  Below is about my laptop. I have 386 gb available.Sent from my iPhoneOn Sep 18, 2023, at 5:30 PM, Aust ***@***.***> wrote:﻿
Hmm haven't seen this one yet. What OS are you using? How much disk space do you have?

**Comment by nyanez1976** [comment]
Ok, i got it to sync!  I had to uninstall the app properly and reinstall. Looks like i had multiple versions of the app but now its synced properly and i just need to connect wallet.  

I do use Defly but all my accounts have ledger attached.    Will see how that goes.
