### ISSUE TITLE
"Enable Telemetry" for Voi Testnet not working 

### ISSUE THREAD

**Issue by MochaN3rd** [AustP/austs-one-click-node#12]
When enabling Telemetry on Voi Testnet using the GUI, it doesn't change the logging.config file. To be clear, I'm on Ubuntu 23.04 and I'm running both Algorand Mainnet and Voi Testnet using this application. I had to locate the logging.config file and manually edit "Enable":False to "Enable":True

**Comment by AustP** [comment]
I think this was solved with the release of v1.4.0. If you run into problems again, please open another issue.
