### ISSUE TITLE
Port 4160 already in use

### ISSUE THREAD

**Issue by RobertSmith8** [AustP/austs-one-click-node#14]
My Algorand Node running on mac is participating in consensus on FF.

When I tried to add a VOI node on testnet I got an error saying port 4160 already in use?

**Comment by AustP** [comment]
You'll need to go to the settings on the Voi node and change the port to be something besides 4160. Lots of people use 4161. Give that a try and let me know.

**Comment by RobertSmith8** [comment]
Thx, I'm up and running VOI and Algorand node now :)
