### ISSUE TITLE
Can't Connect to A-Wallet

### ISSUE THREAD

**Issue by cswenor** [AustP/austs-one-click-node#15]
Synced up my node this morning and tried to connect it to a-wallet. After adding the wallet connect connection to a-wallet the 1CN app didn't recognize as it being connected.

https://github.com/AustP/austs-one-click-node/assets/647451/8bf7656c-0985-43e6-8549-242723c496c1

**Comment by scholtz** [comment]
i experienced this issue some time as well, and i believe it is the defly gateway not working atm

when I used the pera qr code it works fine, however there is little issue with pera that you cannot copy it as text and have to decode the qr code.. the best would be if the direct wallet connect 2 would be supported by the austs node (user may setup his wc2 credentials by him self somewhere in the settings fe)

**Comment by AustP** [comment]
v1.4.1. was just released which fixes this problem.
