### ISSUE TITLE
Loading session falled

### ISSUE THREAD

**Issue by Bencactus1** [AustP/austs-one-click-node#16]
Hi since 2 days i have the issue when i want to connect again my defly wallet , i have reinstal one click node and my defly wallet but the same issue.. 
![image](https://github.com/AustP/austs-one-click-node/assets/154683944/38548cbe-265b-4418-bccf-4b51dfbf07c0)
i use the last version of one click.

**Comment by Xn0xic** [comment]
Commenting for visibility.  I also cannot connect my wallets to my nodes.  Software/firmware are up to date & working with other dAPPs.  Wonder if changes to the Ledger Connect code base a few weeks ago to mitigate the wallet drainer are the cause...

**Comment by Bencactus1** [comment]
but it work for another ? we are alone ?

**Comment by AustP** [comment]
v1.4.1 was just released which fixes the Defly connection issues.
