### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Xn0xic** [AustP/austs-one-click-node#2]
First, many thanks for building this!  It's exactly what we need to increase adoption by lowering the technical knowledge barrier.  I've tried to spin up a node several times using different guides with no success.  I tried Docker, WSL, Rand's windows distro.  Nothing worked, and even the Discord group couldn't help me figure it out.  "Must be a hardware issue"......

I'm not an expert, but certainly a little more tech savvy than most users. No changes to my hardware and your distro works flawlessly.  Three nodes up and running in true one-click fashion.  Bravo!

On to the feature requests:
1) Ability to specify drive/directory for binary installation and working data files.
2) Option to run archive node.

**Comment by AustP** [comment]
Thanks, glad you enjoy it!

As for your feature requests, I'm not sure if they really fit into the one-click node. This really is meant for users who are not tech savvy. For them it doesn't really matter where the data directory or binaries are located. They also probably don't need to be running an archive node. If someone is wanting that level of control over their node, then I think they'd be better off running a node in the more traditional way.

**Comment by EMatthews93** [comment]
> Thanks, glad you enjoy it!
> 
> As for your feature requests, I'm not sure if they really fit into the one-click node. This really is meant for users who are not tech savvy. For them it doesn't really matter where the data directory or binaries are located. They also probably don't need to be running an archive node. If someone is wanting that level of control over their node, then I think they'd be better off running a node in the more traditional way.

This application is absolutely amazing!! How does the foundation not have a solution like this?

I would second the feature request for choosing a drive/directory. I can't run a node on the drive that has my OS (no space), however I can run a node on my second drive.

PS: I think there are tech savvy people that don't yet know, or want to know, the nitty gritty of running a node - they just want to participate.

**Comment by WizardsEnterprise** [comment]
> > Thanks, glad you enjoy it!
> > As for your feature requests, I'm not sure if they really fit into the one-click node. This really is meant for users who are not tech savvy. For them it doesn't really matter where the data directory or binaries are located. They also probably don't need to be running an archive node. If someone is wanting that level of control over their node, then I think they'd be better off running a node in the more traditional way.
> 
> This application is absolutely amazing!! How does the foundation not have a solution like this?
> 
> I would second the feature request for choosing a drive/directory. I can't run a node on the drive that has my OS (no space), however I can run a node on my second drive.
> 
> PS: I think there are tech savvy people that don't yet know, or want to know, the nitty gritty of running a node - they just want to participate.

I also agree with number 1 of the feature request... due to space issues, there are people like me who cannot run this on their OS drive and need to run it on a separate hard drive

**Comment by Xn0xic** [comment]
> Thanks, glad you enjoy it!
> 
> As for your feature requests, I'm not sure if they really fit into the one-click node. This really is meant for users who are not tech savvy. For them it doesn't really matter where the data directory or binaries are located. They also probably don't need to be running an archive node. If someone is wanting that level of control over their node, then I think they'd be better off running a node in the more traditional way.

Thanks for replying.  I see your point with running an archive node, however I humbly request that you revisit directory replacement.  As others have stated, I also have a system that can't support a node on the OS drive but do have capacity on a storage drive on that system.  Technical prowess shouldn't be a barrier to supporting the ecosystem.

**Comment by AustP** [comment]
Good points.

I'll work on adding a setting for it in the next release.

**Comment by AustP** [comment]
v1.4.0 lets you change the data directory now.
