### ISSUE TITLE
Cannot reconnect to a-wallet from node 

### ISSUE THREAD

**Issue by dsp11111** [AustP/austs-one-click-node#20]
I needed to renew my keys because they were expiring .. the first part worked then when I clicked the update keys green button I got the defly popup to connect to the node .. but I never got any prompt to do anything on the node ..  so they told me to click disconnect  on the node .. I did and then when I clicked connect again I got the proper defly connect popup .. I clicked copy as usual .. went  to a-wallet copied the string into wallet connect and I get an entry in the connections section below but no peer is ever generated .. it’s always blank in the wallet connect screen .. so I cannot update my keys .. I tried using screen connect next from the main wallet page and the list of account page .. my keys expire soon .. thx

**Comment by AustP** [comment]
This was resolved by restarting A1CN and then trying the process again.
