### ISSUE TITLE
‘Try Again’ error

### ISSUE THREAD

**Issue by Calibut** [AustP/austs-one-click-node#21]
Node is up and running; however, my node randomly crashes and shows a random ‘Try Again’ error. I am using VPN, could this be the reason? Is there a way to ‘try again’ automatically?

**Comment by AustP** [comment]
The 'Try Again' error pops up when it takes more than 15s for your node to hear about the next block being produced.

If your internet goes down for 20s, for example, you would see this error screen. So it's possible that a VPN could be delaying traffic enough to cause that.

One thing to note, however, is that the node will still try to connect behind this error scene. So if your internet drops out for 20s but then stabilizes, your node will start participating in consensus again even though an error screen is shown. It's on my list of todos to make the error screen go away when the node reconnects.

Right now, if you click the 'Try Again' button and it goes straight back to the dashboard, it means there was a blip in your internet but all is well now. If you click the button and it goes to the syncing page, it means that your node has been down for a while.

**Comment by Rownygd** [comment]
Hi. Can you make it to automatically reconnect after 'Try Again' error ? After the error is displayed I don't see blocks count go up anymore.

**Comment by FleshWhistle** [comment]
> Node is up and running; however, my node randomly crashes and shows a random ‘Try Again’ error. I am using VPN, could this be the reason? Is there a way to ‘try again’ automatically?

Mines been doing this alot lately and i know my internet isnt faulty..now after restarting my laptop it keeps refreshing itself to make sure the node is running and won't catch up on the blocks..

**Comment by AustP** [comment]
In the latest version (v1.4.4) we made it so it auto-retries. I'm gonna close this for now but if you see it happening again, please let me know.
