### ISSUE TITLE
i have no idea whats causeing this

### ISSUE THREAD

**Issue by gooybeef** [AustP/austs-one-click-node#22]
![20240226_000729](https://github.com/AustP/austs-one-click-node/assets/66107194/825b66be-f44d-4342-b9a0-eee2890e3ebd)

im haveing this issue with the voi node ive connected everything and keep getting this 
i imported my kibisis wallet to my defly wallet and this keeps coming up when i connect to defly ?? kibisis wont show up as a connect what do i do do to get the node started??

**Comment by gooybeef** [comment]
same thing comes up when i switch to test net

**Comment by AustP** [comment]
For now, you have to use https://a-wallet.net for the Voi wallet. Defly and Kibisis are not supported for Voi.

**Comment by gooybeef** [comment]
Issue resolved thank you for reaching out node is active and healthy
