### ISSUE TITLE
Node online but...

### ISSUE THREAD

**Issue by FleshWhistle** [AustP/austs-one-click-node#24]
Had to delete and reinstall the app and now I can't generate keys since it constantly checks to see if it's online, so now I can't participate

**Comment by AustP** [comment]
Other people who have had similar issues have solved it by using a VPN if they're not currently using one. Or not using a VPN if they currently use one. Can you try that?

**Comment by bluesuedesw** [comment]
Also had this issue. Keys were about to expire. I could not update my keys from within the A1CN on macOS. The update keys / go offline button was always disabled after regenerating keys.

 Had to completely delete the data directory, uninstall A1CN, reinstall then was able to setup the node again as new.

**Comment by FleshWhistle** [comment]
I got it to work. Im thinking it's actually bc I started using my vpn

**Comment by AustP** [comment]
@bluesuedesw For your issue, it could be that the wallet connect session expired. In that case, your account could've moved to a "Watch Account". The way to make it so you can issue the commands again would be by connecting your account again.

@FleshWhistle Great to hear it
