### ISSUE TITLE
Ledger cannot verify

### ISSUE THREAD

**Issue by JohnKevinK** [AustP/austs-one-click-node#26]
On Pera wallet, using Ledger, I get the error "In-App sdkError(error: Optional(Error Domain=go Code=1 "incorrect signature length expected 64, got 86" UserInfo=(NSlocalizedDescription=incorrect signature length expected 64, got 86})), when Pera attempts to verify the transaction with ledger.

**Comment by AustP** [comment]
We don't support using Pera. We only support Defly. Try using them instead.
