### ISSUE TITLE
Node won't SYNC

### ISSUE THREAD

**Issue by Pableo2022** [AustP/austs-one-click-node#27]
I lost power and the node won't sync past block 39816185.    It will try to sync and then open back up with being on block 39816185 again.  I tried restarting the node, and the computer, deleting the node, and rekeying.  Do you have any suggestions?

**Comment by AustP** [comment]
Maybe something got corrupted when the power was lost. You could try completely uninstalling and then reinstalling the application. Depending on the OS, you may need to manually delete some folders. What OS are you running?

**Comment by Pableo2022** [comment]
I am running IOS Sonoma 14.5.

**Comment by Pableo2022** [comment]
Do you  happen to have an idea on what the file would be called for where the node information is saved?

**Comment by AustP** [comment]
There is another folder: /Users/username/Library/Application Support/Austs One-Click Node.
You can try uninstalling, deleting that folder, and trying again.

**Comment by Pableo2022** [comment]
Thank you! I will give this a try.
