### ISSUE TITLE
How do I remove the whole installtion on macOS and re-install again?

### ISSUE THREAD

**Issue by gimantha** [AustP/austs-one-click-node#28]
I deleted the data directory and the Applications/Aust's-One click Node application. 
Do I need to clear or delete any other folders to reset everything back to like I never installed the one-click node. I want to start it fresh again.
Thanks

**Comment by gimantha** [comment]
<img width="1434" alt="image" src="https://github.com/AustP/austs-one-click-node/assets/9362271/cc5ab110-92f8-4cfe-bf14-05a434afb7e5">

Its forever stuck here. Thats why I want to reset. In the initial installation it asked me to connect the wallet. Now that window never comes

**Comment by AustP** [comment]
There is another folder: /Users/username/Library/Application Support/Austs One-Click Node.
Try deleting that after uninstalling.

**Comment by gimantha** [comment]
> There is another folder: /Users//Library/Application Support/Austs One-Click Node. Try deleting that after uninstalling.

Thats the data folder right? ok..  got it.. thanks.. data folder was inside this one

**Comment by gimantha** [comment]
Problem sorted after deleting everything and syncing fully. Thank you @AustP
