### ISSUE TITLE
Voi Testnet syncing forever

### ISSUE THREAD

**Issue by CoinHatchTech** [AustP/austs-one-click-node#29]
Hi,

Im trying to install nodes for both Algorand and Voi Testnet.
Algorand MainNet node is getting synced in about 3 hours. But Voi TestNet node syncing is going on for ever(It has been >7hrs).
Im attaching the screenshot and please let me know if I need to do something to get my Voi TestNet node synced.

![image](https://github.com/user-attachments/assets/a37d2aac-3111-4a6a-8b23-09ee18d43bb1)

**Comment by AustP** [comment]
I'm not sure why that would happen. I would suggest restarting the application and seeing if that fixes the problem.

**Comment by EMatthews93** [comment]
I have been experiencing this over the last 2 weeks as well. I've restarted, deleted caches, deleted node data, still the same problem at a certain block.

I opened a thread in the Voi Discord about it: https://discord.com/channels/1055863853633785857/1262832599454187531/1264977751614427238

It appears that there's maybe an update that needs to happen.

**Comment by AustP** [comment]
Just released a new version: https://github.com/AustP/austs-one-click-node/releases/tag/v1.4.4
It doesn't completely solve the issue, but it does help.
Give that a try and let me know.
