### ISSUE TITLE
Bug Report- Signing Transactions Time-out

### ISSUE THREAD

**Issue by Xn0xic** [AustP/austs-one-click-node#3]
Attempting to go online with Ledger wallet through Defly times out before transaction can be signed.
Defly wallet without Ledger secured keys works fine.
OS- Windows 11

**Comment by AustP** [comment]
I've upped the timeout from 15s to 30s. Hopefully that will be enough.

**Comment by Xn0xic** [comment]
> I've upped the timeout from 15s to 30s. Hopefully that will be enough.

Thanks!  That did the trick!
