### ISSUE TITLE
Can't participate in consensus

### ISSUE THREAD

**Issue by Rownygd** [AustP/austs-one-click-node#30]
Hi, after downloading v. 1.4.4 I can't participate in consensus via Escrow on Folks Finance. I have green marks on Node being running and synced but yellow mark on "Participating in Consensus".  I've registeded myself for Consensus on Folks Finance as in v. 1.4.3 and everytning was working well. Now it's not.

**Comment by AustP** [comment]
I would suggest generating new keys and going through the registration process again and see if that fixes the issue.
