### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Rownygd** [AustP/austs-one-click-node#37]
Hi, I havn't got any problems for a long time, but today I encounter below error. Can you advise how to resolve it please ?

Error: Command failed: "C:\Users\pawel.rownicki\AppData\Local\austs_one_click_node\app-1.5.0\resources\goal.exe" node catchup -d "C:\Users\pawel.rownicki\AppData\Roaming\Austs One-Click Node\data\algorand.mainnet" 44300000#KQYCH4AQ3Y7QDNDLKMHW2PP73B6ZUJUDLFK7HR7JKKM4YJXRBZSA
Cannot contact Algorand node: HTTP 400 Bad Request: unable to start catchpoint catchup for '44300000#KQYCH4AQ3Y7QDNDLKMHW2PP73B6ZUJUDLFK7HR7JKKM4YJXRBZSA' - already catching up '44180000#TG7XIMBCNPACH67GBXTWK5KA7LM3BBJ5OWDUZGBMBVOLKJBZNYLA'

**Comment by AustP** [comment]
If it's already catching up, it could just take some time to resolve. Try restarting the app after a few hours. If that doesn't work, try restarting your computer. If that doesn't work, the last resort is deleting the "C:\Users\pawel.rownicki\AppData\Roaming\Austs One-Click Node\data\algorand.mainnet" folder and then starting the app again. Doing that will force the app to do a full catchup. You'll have to regenerate keys as well.
