### ISSUE TITLE
Could not start node

### ISSUE THREAD

**Issue by flaming-oranges** [AustP/austs-one-click-node#38]
Hi,

Ive been running a node for about a year now. I am getting this error every time I start it up now. 

Error: Could not start node: listen tcp 0.0.0.0:4160: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

I did install AvmWinNode to see what it looked like, but then uninstalled it. It has been a long time since Ive done any listening port troubleshooting and would be very grateful for some help.

TIA!

**Comment by flaming-oranges** [comment]
I terminated algod and it is now starting. It is now syncing. I will let you know if the problem continues after a reboot.

**Comment by flaming-oranges** [comment]
So AvmWinNode adds algod as a service, but doesnt disable it when you uninstall AvmWinNode. I had to go into sewrvices and change it to Manual. Everything is good now.

**Comment by AustP** [comment]
Glad to hear that you got it figured out. If you ever have port issues in the future, you can always change the port in the settings of the app. It defaults to 4160 because that is algod's default but it will work on any port as long as it's not in use by another program.
