### ISSUE TITLE
Go Online Error

### ISSUE THREAD

**Issue by GovVoi** [AustP/austs-one-click-node#4]
I've tried to go online for awhile and I get this error. I believe I've followed the process to connect wallet properly and generated keys.  Any suggestions welcome to make the final step.  
![Screenshot 2023-08-29 232817](https://github.com/AustP/austs-one-click-node/assets/143576762/4fc76d05-c535-44d9-8deb-c9323c0b0cff)

**Comment by AustP** [comment]
Were you able to get it running? On Twitter it looked like somehow your node skipped to the dashboard before syncing. Did restarting the app work?

**Comment by AustP** [comment]
Restarting the app did indeed work.
