### ISSUE TITLE
Austs One-Click Node has stopped working

### ISSUE THREAD

**Issue by WizardsEnterprise** [AustP/austs-one-click-node#6]
![os](https://github.com/AustP/austs-one-click-node/assets/31045125/737be7c5-6071-476f-8fdd-0de1c6f42495)
![err1](https://github.com/AustP/austs-one-click-node/assets/31045125/03838006-4e49-4a09-8108-7a1325d45fff)
![err2](https://github.com/AustP/austs-one-click-node/assets/31045125/4f182714-0c12-44cb-b1c2-5accc79227db)

**Comment by AustP** [comment]
Thanks for the report. Looks like there was a memory leak when turning telemetry on (see #10). Were you using telemetry on your node by chance?

**Comment by WizardsEnterprise** [comment]
It will not allow me to install on Windows Server 2012 R2 So I never got to the point of being able to run the node at all

**Comment by AustP** [comment]
Recapping our Discord thread here.

https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice shows that Electron 22 is the last version that supports Windows Server 2012 R2. This project uses Electron 25. I downgraded the project to Electron 22 and sent Wizard a build. They got it to install/start but got an error "fetch is not defined".

We use `fetch` to interact with the node via goal's REST API so downgrading is not an option.

We could swap out `fetch` with `XMLHttpRequest` but seeing as Windows Server 2012 R2 reaches EOL in less than a month, it's not worth the hassle.
