### ISSUE TITLE
Node Cannot Be Synced

### ISSUE THREAD

**Issue by WizardsEnterprise** [AustP/austs-one-click-node#7]
Error: Command failed: "C:\Users\cliff\AppData\Local\austs_one_click_node\app-1.3.0\resources\goal.exe" node catchup -d "C:\Users\cliff\AppData\Roaming\Austs One-Click Node\data\algorand.mainnet" 32100000#SDKT4X5CCU3TJ24QGLWQFMCQTJQFNIUTZTQELFAMAJ26BWNKZ2OA
Cannot contact Algorand node: HTTP 400 Bad Request: unable to start catchpoint catchup for '32100000#SDKT4X5CCU3TJ24QGLWQFMCQTJQFNIUTZTQELFAMAJ26BWNKZ2OA' - already catching up '32090000#5CZOYUGTR2UGKRIGKZWLXQT7X3ENX4UBYTIAJBFPCAMDYWCMSZYA'

![os2](https://github.com/AustP/austs-one-click-node/assets/31045125/357b6a53-0711-44f1-a1e3-4846e719e44e)
![free space](https://github.com/AustP/austs-one-click-node/assets/31045125/8794df1c-6d0b-458d-95ce-322c7aa72c46)
![speed](https://github.com/AustP/austs-one-click-node/assets/31045125/6f1d0e62-d813-4c6c-b12c-816d8d649254)
![err3](https://github.com/AustP/austs-one-click-node/assets/31045125/95997acf-8fac-45a0-96b5-9dba77a4ac79)

**Comment by AustP** [comment]
I'm not exactly sure why this happens. I think it may be a race condition that happens when changing settings while the node is currently syncing. Did you do that perhaps? And after it finished syncing, did the app work as expected?

**Comment by Algocleanup** [comment]
I clicked on the settings during the sync but didn't change anything. After 12 hours of syncing, I received the same error.

**Comment by AustP** [comment]
Can you open the config.json and bump the MaxCatchpointDownloadDuration value up from `43200000000000` to `432000000000000`? (add a 0) and restart the node?

**Comment by AustP** [comment]
I just was this happen again. It seems like it is a caching issue. If you're okay doing a complete resync, you can:

1. Make sure A1CN is not running.
2. Delete the C:\Users\<username>\AppData\Roaming\Austs One-Click Node folder.
3. Start the app again.
