### ISSUE TITLE
Ability to change install location

### ISSUE THREAD

**Issue by stangoAlgo** [AustP/austs-one-click-node#9]
A1CN for windows default installs to my c: drive (my OS drive) which only has 22gb free. 
I believe that this causes memory issues when telemetry is turned on.
My machine has 32 gb of ram
The memory issue being caused is that the node will consume all available memory when telemetry is turned on, and then will crash. 

 I would like to be able to easily change the install location to another drive which has almost 1 tb free.

**Comment by AustP** [comment]
Good idea. #2 also brought this up so I'll track it there.
